# Generated by Django 3.2.18 on 2023-03-05 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtraInfo',
            new_name='UserProfile',
        ),
    ]
