# Generated by Django 3.2.18 on 2023-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeetasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetasks',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
