# Generated by Django 3.2.18 on 2023-05-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_employeetasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeTasks',
        ),
    ]
